### ISSUE TITLE
FFI failure due to Headers() not existing

### ISSUE THREAD

**Issue by Gavinok** [rowtype-yoga/purescript-fetch#4]
Ran a pretty basic example 
```purescript
module Main where

import Prelude
import Effect (Effect)
import Effect.Aff (launchAff_)
import Effect.Class (liftEffect)
import Effect.Console (log)
import Fetch (fetch)

main :: Effect Unit
main =
  launchAff_ do
    { status, text } <-
      fetch "https://httpbin.org/get"
        { headers: { "Content-Type": "applications/json" } }
    responsText <- text
    liftEffect do
      log responsText
```
and got this error
```
ReferenceError: Headers is not defined
    at Module.unsafeNew (file:///home/gavinok/.local/Dropbox/Programming/purescript/real-fetch/output/Fetch.Core.Headers/foreign.js:2:3)
    at __do (file:///home/gavinok/.local/Dropbox/Programming/purescript/real-fetch/output/Fetch.Core.Headers/index.js:25:33)
    at Module.unsafePerformEffect (file:///home/gavinok/.local/Dropbox/Programming/purescript/real-fetch/output/Effect.Unsafe/foreign.js:2:10)
    at file:///home/gavinok/.local/Dropbox/Programming/purescript/real-fetch/output/Fetch.Core.Headers/index.js:24:30
    at file:///home/gavinok/.local/Dropbox/Programming/purescript/real-fetch/output/Fetch.Core.Headers/index.js:37:70
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:533:24)
    at async loadESM (node:internal/process/esm_loader:91:5)
    at async handleMainPromise (node:internal/modules/run_main:65:12)
[error] Running failed; exit code: 1
```

**Comment by Gavinok** [comment]
My mistake didn't run the the experimental fetch setting
